### ISSUE TITLE
As a user I can filter consultants based on certifications

### ISSUE THREAD

**Issue by savalre** [Cast2023/cast#13]
## Details
- possibility to search for consultants based on their certifications in Search page (frontend)
- see Jiisala comment below for more details
- needed arrangements in backend

## Estimation
TBD

## Acceptance criteria 
The feature fulfils the DoD - criteria. The feature is demonstrated to a client from staging environment. After clients approval feature is deployed to production server.

**Comment by Jiisala** [comment]
Search by Vendor combined with open textfield
First show all consultants wit certificate from vendor, then another filter for more details.
