### ISSUE TITLE
As a user I can import certificates from spreadsheet

### ISSUE THREAD

**Issue by maijams** [Cast2023/cast#76]
## Details
- spreadsheet data is processed, validated and inserted into db tables in backend
- see Jiisala comments below

## Estimation
TBD

## Acceptance criteria 
The feature fulfils the DoD - criteria. The feature is demonstrated to a client from staging environment. After clients approval feature is deployed to production server.

**Comment by Jiisala** [comment]
Vendor based / Unique Certificate based search.
Adding with dropdown or autocomplete. 
Must show end-date if available. 
At later point even (automatic) alert for expiration date.
